export const NewRecipeMockData = [
    { id: 0, title: 'Салаты' },
    { id: 1, title: 'Закуски' },
    { id: 2, title: 'Первые блюда' },
    { id: 3, title: 'Вторые блюда' },
    { id: 4, title: 'Десерты, выпечка' },
    { id: 5, title: 'Блюда на гриле' },
    { id: 6, title: 'Веганская кухня' },
    { id: 7, title: 'Детские блюда' },
    { id: 8, title: 'Лечебное питание' },
    { id: 9, title: 'Национальные' },
    { id: 10, title: 'Соусы' },
    { id: 11, title: 'Напитки' },
    { id: 12, title: 'Заготовки' },
];
