import bread from '../../../public/bread.png';
import childTasty from '../../../public/childTasty.png';
import dishWasher from '../../../public/dishWasher.png';
import Eggplant from '../../../public/Eggplant.png';
import healthyEating from '../../../public/healthyEating.png';
import internationalFood from '../../../public/internationalFood.png';
import kitchen from '../../../public/kitchen.png';
import leaf from '../../../public/leaf.png';
import mortar from '../../../public/mortar.png';
import pan from '../../../public/pan.png';
import pasta from '../../../public/pasta.png';
import pot from '../../../public/pot.png';
import teaCup from '../../../public/teaCup.png';

export const NavMenuData = [
    {
        id: 1,
        title: 'Салаты',
        icon: Eggplant,
        childrens: [
            { id: 1, title: 'Мясные салаты' },
            { id: 2, title: 'Рыбные салаты' },
            { id: 3, title: 'Овощные салаты' },
            { id: 4, title: 'Теплые салаты' },
        ],
    },
    {
        id: 2,
        title: 'Закуски',
        icon: healthyEating,
        childrens: [
            { id: 1, title: 'Мясные закуски' },
            { id: 2, title: 'Рыбные закуски' },
            { id: 3, title: 'Овощные закуски' },
            { id: 4, title: 'Теплые закуски' },
            { id: 5, title: 'Бутерброды' },
            { id: 6, title: 'Фастфуд' },
        ],
    },
    {
        id: 3,
        title: 'Первые блюда',
        icon: pot,
        childrens: [
            { id: 1, title: 'Мясные супы' },
            { id: 2, title: 'Овощные супы' },
            { id: 3, title: 'Бульоны' },
            { id: 4, title: 'Холодные супы' },
            { id: 5, title: 'Диетические супы' },
        ],
    },
    {
        id: 4,
        title: 'Вторые блюда',
        icon: pan,
        childrens: [
            { id: 1, title: 'Мясные' },
            { id: 2, title: 'Рыбные' },
            { id: 3, title: 'Овощные' },
            { id: 4, title: 'Из птицы' },
            { id: 5, title: 'Из грибов' },
            { id: 6, title: 'Из субпродуктов' },
            { id: 7, title: 'На пару' },
            { id: 8, title: 'Пельмени, вареники' },
            { id: 9, title: 'Мучные гарниры' },
            { id: 10, title: 'Овощные гарниры' },
            { id: 11, title: 'Пицца' },
            { id: 11, title: 'Суши' },
        ],
    },
    {
        id: 5,
        title: 'Десерты, выпечка',
        icon: bread,
        childrens: [
            { id: 1, title: 'Блины и оладьи' },
            { id: 2, title: 'Пироги и пончики' },
            { id: 3, title: 'Торты' },
            { id: 4, title: 'Рулеты' },
            { id: 5, title: 'Кексы и маффины' },
            { id: 6, title: 'Сырники и ватрушки' },
            { id: 7, title: 'Из слоеного теста' },
            { id: 8, title: 'Из заварного теста' },
            { id: 9, title: 'Из дрожжевого теста' },
            { id: 10, title: 'Булочки и сдоба' },
            { id: 11, title: 'Хлеб' },
            { id: 12, title: 'Тесто на пиццу ' },
            { id: 13, title: 'Кремы' },
        ],
    },
    {
        id: 6,
        title: 'Блюда на гриле',
        icon: dishWasher,
        childrens: [
            { id: 1, title: 'Говядина' },
            { id: 2, title: 'Свинина' },
            { id: 3, title: 'Птица' },
            { id: 4, title: 'Рыба' },
            { id: 5, title: 'Грибы' },
            { id: 6, title: 'Овощи' },
        ],
    },
    {
        id: 7,
        title: 'Веганская кухня',
        icon: leaf,
        childrens: [
            { id: 1, title: 'Закуски' },
            { id: 2, title: 'Первые блюда' },
            { id: 3, title: 'Вторые блюда' },
            { id: 4, title: 'Гарниры' },
            { id: 5, title: 'Десерты' },
            { id: 6, title: 'Выпечка' },
            { id: 7, title: 'Сыроедческие блюда' },
            { id: 8, title: 'Напитки' },
        ],
    },
    {
        id: 8,
        title: 'Детские блюда',
        icon: childTasty,
        childrens: [
            { id: 1, title: 'Первые блюда' },
            { id: 2, title: 'Вторые блюда' },
            { id: 3, title: 'Гарниры' },
            { id: 4, title: 'Выпечка' },
            { id: 5, title: 'Без глютена' },
            { id: 6, title: 'Без сахара' },
            { id: 7, title: 'Без аллергенов' },
            { id: 8, title: 'Блюда для прикорма' },
        ],
    },
    {
        id: 9,
        title: 'Лечебное питание',
        icon: kitchen,
        childrens: [
            { id: 1, title: 'Детская диета' },
            { id: 2, title: 'Диета №1' },
            { id: 3, title: 'Диета №2' },
            { id: 4, title: 'Диета №3' },
            { id: 5, title: 'Диета №5' },
            { id: 6, title: 'Диета №6' },
            { id: 7, title: 'Диета №7' },
            { id: 8, title: 'Диета №8' },
            { id: 9, title: 'Диета №9' },
            { id: 10, title: 'Диета №10' },
            { id: 11, title: 'Диета №11' },
            { id: 12, title: 'Диета №11' },
            { id: 13, title: 'Диета №12' },
            { id: 14, title: 'Диета №13' },
            { id: 15, title: 'Диета №14' },
            { id: 16, title: 'Без глютена' },
            { id: 17, title: 'Без аллергенов' },
        ],
    },
    {
        id: 10,
        title: 'Национальные',
        icon: internationalFood,
        childrens: [
            { id: 1, title: 'Американская кухня' },
            { id: 2, title: 'Армянская кухня' },
            { id: 3, title: 'Греческая кухня' },
            { id: 4, title: 'Грузинская кухня' },
            { id: 5, title: 'Итальянская кухня' },
            { id: 6, title: 'Испанская кухня' },
            { id: 7, title: 'Китайская кухня' },
            { id: 8, title: 'Мексиканская кухня' },
            { id: 9, title: 'Паназиатская кухня' },
            { id: 10, title: 'Русская кухня' },
            { id: 11, title: 'Турецкая кухня' },
            { id: 12, title: 'Французская кухня' },
            { id: 13, title: 'Шведская кухня' },
            { id: 14, title: 'Японская кухня' },
            { id: 15, title: 'Другая кухня' },
        ],
    },
    {
        id: 11,
        title: 'Соусы',
        icon: mortar,
        childrens: [
            { id: 1, title: 'Соусы мясные' },
            { id: 2, title: 'Соусы сырные' },
            { id: 3, title: 'Маринады' },
        ],
    },
    {
        id: 12,
        title: 'Напитки',
        icon: teaCup,
        childrens: [
            { id: 1, title: 'Мясные заготовки' },
            { id: 2, title: 'Рыбные заготовки' },
            { id: 3, title: 'Из огурцов' },
            { id: 4, title: 'Из томатов' },
            { id: 5, title: 'Из грибов' },
            { id: 6, title: 'Овощные заготовки' },
            { id: 7, title: 'Салаты, икра' },
            { id: 8, title: 'Из фруктов и ягод' },
        ],
    },
    {
        id: 13,
        title: 'Заготовки',
        icon: pasta,
        childrens: [
            { id: 1, title: 'Соки и фреши' },
            { id: 2, title: 'Смузи' },
            { id: 3, title: 'Компоты' },
            { id: 4, title: 'Кисели' },
            { id: 5, title: 'Кофе' },
            { id: 6, title: 'Лечебный чай' },
            { id: 7, title: 'Квас' },
            { id: 8, title: 'Коктейли' },
            { id: 9, title: 'Алкогольные' },
        ],
    },
];
