export enum ApiEndpoints {
    POSTS = '/posts/',
    CATEGORIES = '/category',
    RECIPES = '/recipe/',
    TEST = '/recipe',
    AUTH = '/auth/login',
    REGISTER = '/auth/signup',
    RESTORE = '/auth/forgot-password',
    VERIFYOTP = '/auth/verify-otp',
    RESETPASSWORD = '/auth/reset-password',
    UPLOAD = '/file/upload',
    REFRESHTOKEN = '/auth/refresh',
    CHECKTOKEN = '/auth/check-auth',
    MEASURE_UNITS = '/measure-units',
}
